spring:
  application:
    name: custom-text-service
  datasource:
    driver-class: org.h2.Driver
    url:jdbc: h2:mem:db-embedded;DB_CLOSE_DELAY=-1
    username: sa
    password: password

server:
  port: ${port:9092}