spring:
  application:
    name: system-api-gateway-service
  cloud:
    gateway:
      routes:
        - id: custom-text-service
          uri: http://localhost:9090/
          predicates:
            - Path=/text/**
        - id: custom-greeting-service
          uri: http://localhost:8080/
          predicates:
            - Path=/greeting/**

server:
  port: ${port:8090}